import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css"; // Assurez-vous que le chemin vers globals.css est correct

// Importation des polices locales avec les variables CSS
const geistSans = localFont({
  src: "./fonts/GeistVF.woff", // Chemin vers la police GeistVF.woff
  variable: "--font-geist-sans", // Variable CSS pour la police sans-serif
  weight: "100 900", // Poids des caractères
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff", // Chemin vers la police GeistMonoVF.woff
  variable: "--font-geist-mono", // Variable CSS pour la police monospace
  weight: "100 900", // Poids des caractères
});

export const metadata: Metadata = {
  title: "Create Next App", // Titre de la page
  description: "Generated by create next app", // Description de la page
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode; // Les enfants de ce layout
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`} // Utilisation des variables de polices avec des classes
      >
        {children}
      </body>
    </html>
  );
}
